[build.environment]
SECRETS_SCAN_OMIT_KEYS = "FINNHUB_API_KEY"

[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  functions = "netlify/functions"
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
